export const ERROR_CODES = {
  UNKNOWN: "UNKNOWN",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  CONFIGURATION_ERROR: "CONFIGURATION_ERROR",
  STORAGE_READ_FAILED: "STORAGE_READ_FAILED",
  STORAGE_WRITE_FAILED: "STORAGE_WRITE_FAILED",
  STORAGE_REMOVE_FAILED: "STORAGE_REMOVE_FAILED",
  API_REQUEST_FAILED: "API_REQUEST_FAILED",
  API_TIMEOUT: "API_TIMEOUT",
  API_NETWORK_ERROR: "API_NETWORK_ERROR",
  API_UNAUTHORIZED: "API_UNAUTHORIZED",
  API_FORBIDDEN: "API_FORBIDDEN",
  API_NOT_FOUND: "API_NOT_FOUND",
  API_SERVER_ERROR: "API_SERVER_ERROR",
  API_BAD_RESPONSE: "API_BAD_RESPONSE",
  WEBSOCKET_CONNECTION_FAILED: "WEBSOCKET_CONNECTION_FAILED",
  WEBSOCKET_DISCONNECTED: "WEBSOCKET_DISCONNECTED",
  WEBSOCKET_MESSAGE_ERROR: "WEBSOCKET_MESSAGE_ERROR",
  EVENT_HANDLER_ERROR: "EVENT_HANDLER_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export function getErrorCodeFromStatus(status: number): ErrorCode {
  if (status === 401) return ERROR_CODES.API_UNAUTHORIZED;
  if (status === 403) return ERROR_CODES.API_FORBIDDEN;
  if (status === 404) return ERROR_CODES.API_NOT_FOUND;
  if (status >= 500) return ERROR_CODES.API_SERVER_ERROR;
  return ERROR_CODES.API_REQUEST_FAILED;
}
